Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -49,17 +49,16 @@ exit_on_signal_SIGTERM () {
 trap exit_on_signal_SIGINT SIGINT
 trap exit_on_signal_SIGTERM SIGTERM
 
-## Install theme-style1
-install_theme-style1 () {
-	{ echo ${ORANGE}" [*] Installing theme-style1..."${CYAN}; echo; }
-	if [[ -f $PREFIX/bin/zsh]]; then
-		{ echo ${GREEN}" [*] theme-style1 is already Installed!"; echo; }
+## Install ZSH
+install_zsh () {
+	{ echo ${ORANGE}" [*] Installing ZSH..."${CYAN}; echo; }
+	if [[ -f $PREFIX/bin/zsh ]]; then
+		{ echo ${GREEN}" [*] ZSH is already Installed!"; echo; }
 	else
-		{ pkg update -y; pkg install -y theme-style1; }
-		(type -p theme-style1 &> /dev/null) && { echo; echo ${GREEN}" [*] Succesfully Installed!"; echo; } || { echo; echo ${RED}" [!] Error Occured,theme-style1 is not installed."; echo; reset_color; exit 1; }
+		{ pkg update -y; pkg install -y zsh; }
+		(type -p zsh &> /dev/null) && { echo; echo ${GREEN}" [*] Succesfully Installed!"; echo; } || { echo; echo ${RED}" [!] Error Occured, ZSH is not installed."; echo; reset_color; exit 1; }
 	fi
 }
-
 ## Backup user settings
 backup_tmux () {
 	if [[ ! -d "$HOME/.termux" ]]; then
